spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalogue-service-route
              uri: lb://market-catalogue-service
              predicates:
                - Host=**catalogue.api.nvgrig.ru**
            - id: feedback-service-route
              uri: lb://market-feedback-service
              predicates:
                - Host=**feedback.api.nvgrig.ru**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8082/realms/market
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: UmagcDHJ3PqiWCLr73BH1T0S99tn0Qbe
            authorization-grant-type: client_credentials
            scope:
              - discovery
server:
  port: 8086
  forward-headers-strategy: framework
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    register-with-eureka: false
