market:
  service:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  application:
    name: market-manager-app
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8082/realms/market
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8082/realms/market
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: DhsFC50IXFDItvZc25VlYM65bcaknW36
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0