market:
  service:
    catalogue:
      uri: lb://market-catalogue-service
    feedback:
      uri: lb://market-feedback-service
spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/market
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/market
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: UKUNilO8jhlzJGDbbEqkiDSqJAFHGmto
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app
            client-secret: UKUNilO8jhlzJGDbbEqkiDSqJAFHGmto
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: customer-app
            client-secret: UKUNilO8jhlzJGDbbEqkiDSqJAFHGmto
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/