spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/market
      client:
        registration:
          keycloak:
            client-id: catalogue-service
            client-secret: EKXWtvOpST737eALxRxGnxNei8iMDv20
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/market

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: catalogue-service
          service-host-type: ip
        url: http://localhost:8085
  application:
    name: market-catalogue-service
server:
  port: 8081
logging:
  level:
    sql: info
springdoc:
  swagger-ui:
    oauth:
      client-id: catalogue-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:8082
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0