spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/market
      client:
        registration:
          keycloak:
            client-id: catalogue-service
            client-secret: EKXWtvOpST737eALxRxGnxNei8iMDv20
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: catalogue-service
            client-secret: EKXWtvOpST737eALxRxGnxNei8iMDv20
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/market
  boot:
    admin:
      client:
        enabled: false
logging:
  level:
    sql: info
springdoc:
  swagger-ui:
    oauth:
      client-id: catalogue-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:8082
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/